### PR TITLE
Update compare_ans_dbl_unc.m and Live Scripts replaced by m-files.

### PR DESCRIPTION
**Pull request by wollmich**
- Different dimensions exception added.
- Old error message: FAILED: different size. Expected 1-by-1, but got 1-by-1.
- New error message: FAILED: different dimensions. Expected 2, but got 1.

### CODE REVIEW

**Comment by wollmich** [comment]
image
A m-file can be opened as a live script.

**Comment by wollmich** [comment]
Sorry I forgot to create two new branches. The next time I will create two different pull requests.

**Comment by wollmich** [comment]
I'll first create a new branch and then I'll open another pull request.

**Comment by DionTimmermann** [comment]
Sorry, I was so busy with the changes to https://github.com/wollmich/metas-unclib-matlab-wrapper , I did not see your pull-request and comments. 

Thank you!

**Pull request closed without merging**
